trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: landingzone
  - name: terraformVersion
    value: '1.5.7'

stages:
- stage: DeployManagementGroups
  displayName: 'Deploy Management Groups Module'
  jobs:
  - job: Deploy
    displayName: 'Deploy managementgroups module'
    timeoutInMinutes: 15
    cancelTimeoutInMinutes: 15
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
    - script: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      displayName: 'Install Azure CLI'
    - script: |
        wget https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
        unzip terraform_$(terraformVersion)_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform -version
      displayName: 'Install Terraform'
    - script: |
        export TF_VAR_decommissioned_management_group_display_name=$(TF_VAR_decommissioned_management_group_display_name)
        export TF_VAR_decommissioned_management_group_name=$(TF_VAR_decommissioned_management_group_name)
        export TF_VAR_environments_management_group_display_name=$(TF_VAR_environments_management_group_display_name)
        export TF_VAR_environments_management_group_name=$(TF_VAR_environments_management_group_name)
        export TF_VAR_platform_management_group_display_name=$(TF_VAR_platform_management_group_display_name)
        export TF_VAR_platform_management_group_name=$(TF_VAR_platform_management_group_name)
        export TF_VAR_root_management_group_display_name=$(TF_VAR_root_management_group_display_name)
        export TF_VAR_root_management_group_name=$(TF_VAR_root_management_group_name)
        export TF_VAR_sandbox_management_group_display_name=$(TF_VAR_sandbox_management_group_display_name)
        export TF_VAR_sandbox_management_group_name=$(TF_VAR_sandbox_management_group_name)
        export TF_VAR_top_level_management_group_prefix=$(TF_VAR_top_level_management_group_prefix)
        export TF_VAR_top_level_management_group_suffix=$(TF_VAR_top_level_management_group_suffix)
        export TF_VAR_top_level_management_group_display_name=$(TF_VAR_top_level_management_group_display_name)
        export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
        export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
        export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
        export ARM_TENANT_ID=$(ARM_TENANT_ID)
        cd modules/managementgroups
        terraform init
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
      displayName: 'Deploy managementgroups module'
