name: MSDO
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sample:
    name: Microsoft Security DevOps

    # Windows and Linux agents are supported
    runs-on: windows-latest

    permissions:
      contents: read
      id-token: write
      actions: read
      # Write access for security-events is only required for customers looking for MSDO results to appear in the codeQL security alerts tab on GitHub (Requires GHAS)
      security-events: write

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v3

      # List files in sourceRoot
    - name: List files in sourceRoot
      run: dir modules

      # Run analyzers
    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@latest
      id: msdo
      # with:
      #   categories: IaC
      #   tools: checkov,terrascan

    - name: Scan Terraform code in modules/managementgroups with Terrascan
      run: |
        curl -sL https://github.com/tenable/terrascan/releases/latest/download/terrascan_windows_amd64.exe -o terrascan.exe
        ./terrascan.exe scan -d modules/managementgroups --output sarif > terrascan-results.sarif
      shell: bash

    - name: Upload Terrascan SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: terrascan-results.sarif

      # Upload alerts to the Security tab - required for MSDO results to appear in the codeQL security alerts tab on GitHub (Requires GHAS)
    - name: Upload alerts to Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      # Upload alerts file as a workflow artifact - required for MSDO results to appear in the codeQL security alerts tab on GitHub (Requires GHAS)
    - name: Upload alerts file as a workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}
