name: MSDO
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sample:
    name: Microsoft Security DevOps

    # Windows and Linux agents are supported
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      actions: read
      # Write access for security-events is only required for customers looking for MSDO results to appear in the codeQL security alerts tab on GitHub (Requires GHAS)
      security-events: write

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v3

      # Run analyzers
    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@latest
      id: msdo

    - name: Scan Terraform code in modules/managementgroups with Terrascan
      run: |
        TERRASCAN_VERSION="v1.19.0"
        wget "https://github.com/tenable/terrascan/releases/download/${TERRASCAN_VERSION}/terrascan_linux_amd64" -O terrascan
        chmod +x terrascan
        ./terrascan scan -d modules/managementgroups --output sarif > terrascan-results.sarif
      shell: bash

    - name: Upload Terrascan SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: terrascan-results.sarif

      # Upload alerts to the Security tab - required for MSDO results to appear in the codeQL security alerts tab on GitHub (Requires GHAS)
    - name: Upload alerts to Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      # Upload alerts file as a workflow artifact - required for MSDO results to appear in the codeQL security alerts tab on GitHub (Requires GHAS)
    - name: Upload alerts file as a workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}
