name: LZ Management Groups Deployment

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  id-token: write

env:
  terraformVersion: '1.5.7'

jobs:
  plan-managementgroups:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: azure/login@v2.1.0
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          audience: api://AzureADTokenExchange

      - uses: hashicorp/setup-terraform@v3.1.0
        with:
          terraform_version: ${{ env.terraformVersion }}

      - name: Run tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          cd modules/managementgroups
          tflint --init
          tflint

      - name: Run tfsec
        shell: bash
        run: |
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash -s -- -b /usr/local/bin
          cd modules/managementgroups
          tfsec .

      - name: Run bootstrap script for creating storage for statefile
        run: |
          chmod +x modules/managementgroups/bootstrap.sh
          modules/managementgroups/bootstrap.sh

      - name: Terraform Init
        uses: hashicorp/terraform-github-action@v1.0.0
        with:
          tf_actions_version: 1.0.0
          tf_actions_subcommand: 'init'
          working-directory: 'modules/managementgroups'
          tf_actions_working_dir: 'modules/managementgroups'
          tf_actions_cli_credentials_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_backend_resource_group_name: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
          TF_VAR_backend_storage_account_name: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
          TF_VAR_backend_container_name: ${{ secrets.BACKEND_CONTAINER_NAME }}
          TF_VAR_backend_key: managementgroups.terraform.tfstate

      - name: Terraform Plan management groups
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_backend_resource_group_name: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
          TF_VAR_backend_storage_account_name: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
          TF_VAR_backend_container_name: ${{ secrets.BACKEND_CONTAINER_NAME }}
          TF_VAR_backend_key: managementgroups.terraform.tfstate
        run: |
          cd modules/managementgroups
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan.txt  

      - name: List files for debug
        run: ls -al modules/managementgroups

      - name: Upload lock file artifact
        uses: actions/upload-artifact@v4
        with:
          name: lockfile-artifact
          path: modules/managementgroups/.terraform.lock.hcl

      - name: Upload plan.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: plan-txt-artifact
          path: modules/managementgroups/plan.txt

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-artifact
          path: modules/managementgroups/tfplan

  manual-approval:
    needs: plan-managementgroups
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval before apply
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mohitsharma911
          minimum-approvals: 1
          issue-title: "Manual approval required for management group apply"
          issue-body: "Please approve to proceed with Terraform apply for management groups."
          exclude-workflow-initiator-as-approver: false

  apply-managementgroups:
    needs: manual-approval
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: azure/login@v2.1.0
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          audience: api://AzureADTokenExchange

      - uses: hashicorp/setup-terraform@v3.1.0
        with:
          terraform_version: ${{ env.terraformVersion }}

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-artifact
          path: modules/managementgroups

      - name: Download plan.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: plan-txt-artifact
          path: modules/managementgroups

      - name: Download lock file artifact
        uses: actions/download-artifact@v4
        with:
          name: lockfile-artifact
          path: modules/managementgroups

      - name: Terraform Apply management groups
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_backend_resource_group_name: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
          TF_VAR_backend_storage_account_name: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
          TF_VAR_backend_container_name: ${{ secrets.BACKEND_CONTAINER_NAME }}
          TF_VAR_backend_key: managementgroups.terraform.tfstate
        run: |
          cd modules/managementgroups
          terraform apply -auto-approve tfplan

      - name: Terraform Drift Detection
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_backend_resource_group_name: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
          TF_VAR_backend_storage_account_name: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
          TF_VAR_backend_container_name: ${{ secrets.BACKEND_CONTAINER_NAME }}
          TF_VAR_backend_key: managementgroups.terraform.tfstate
        run: |
          cd modules/managementgroups
          terraform init -reconfigure \
            -backend-config="resource_group_name=${TF_VAR_backend_resource_group_name}" \
            -backend-config="storage_account_name=${TF_VAR_backend_storage_account_name}" \
            -backend-config="container_name=${TF_VAR_backend_container_name}" \
            -backend-config="key=${TF_VAR_backend_key}"
          terraform plan -detailed-exitcode

      - name: Terraform Apply Drift Remediation
        if: ${{ steps.terraform_drift_detection.outcome == 'failure' }}
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          cd modules/managementgroups
          terraform apply -auto-approve